@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
@FieldsAreNonnullByDefault
package binnie.extrabees;

import javax.annotation.ParametersAreNonnullByDefault;

import binnie.extrabees.utils.FieldsAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;